# Generated by Django 5.1.3 on 2024-11-16 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'search1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Search2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'search2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Search3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'search3',
                'managed': False,
            },
        ),
    ]
